In [1]:
import cv2
import numpy

C:\Users\Aakash Chandra\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Aakash Chandra\anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\Aakash Chandra\anaconda3\lib\site-packages\numpy\.libs\libopenblas.QVLO2T66WEPI7JZ63PS3HMOHFEY472BC.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:\n%s" %


# Contours


## Reading Image and Convert to Gray 


In [11]:
im = cv2.imread('opencv.png')
imgray = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
cv2.imshow("Logo b/w",imgray)
cv2.waitKey(0)
cv2.destroyAllWindows()


## Apply Thresholding


In [12]:
ret, thresh = cv2.threshold(imgray, 250, 255, 0)
cv2.imshow("Logo b/w",thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

 ## Find Contours
cv2.findContours is used to find contours.As the arguments for the function first one is source image, second is contour retrieval mode, third is contour approximation method.The contours variable holds the contours found in the image and each contour is a array of points joining which would give us the boundary

In [20]:
contours, _ = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
#No of Contours in the image
print(len(contours))
print(_)

13
[[[-1 -1  1 -1]
  [ 2 -1 -1  0]
  [ 4  1  3  0]
  [-1 -1 -1  2]
  [ 6  2  5  0]
  [-1 -1 -1  4]
  [ 7  4 -1  0]
  [ 8  6 -1  0]
  [10  7  9  0]
  [-1 -1 -1  8]
  [11  8 -1  0]
  [12 10 -1  0]
  [-1 11 -1  0]]]


## Draw Contours
Done using the cv2.drawContours method . Takes arguments as the image, the set of points, the color of the contour and the thickness of the line

In [14]:
cv2.drawContours(im, contours, -1, (255,255,0), 3)
cv2.imshow("Image with contours",im)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Motion Detection and Tracking


## Reading and Displaying a Video

In [17]:
cap=cv2.VideoCapture("Cars Moving On Road Stock Footage - Free Download.mp4")
while cap.isOpened():
    ret,frame=cap.read()
    cv2.imshow("Video",frame)
    if cv2.waitKey(40)==27:
        break

cv2.destroyAllWindows()
cap.release()


# Reading two frames

In [23]:
cap=cv2.VideoCapture("Cars Moving On Road Stock Footage - Free Download.mp4")
ret,frame1=cap.read()
ret,frame2=cap.read()
while cap.isOpened():
    diff=cv2.absdiff(frame1,frame2)#Difference between Frames
    gray=cv2.cvtColor(diff,cv2.COLOR_BGR2GRAY)#Convert to Grayscale
    blur=cv2.GaussianBlur(gray,(5,5),0)#Blur it
    _,thresh=cv2.threshold(blur,20,255,cv2.THRESH_BINARY)#Thresholding
    dilated=cv2.dilate(thresh,None,iterations=3)#Dilation
    contours,_=cv2.findContours(dilated,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)#Finding Contours
    #cv2.drawContours(frame1,contours,-1,(0,255,0),2)
    #Drawing Bounding Box for each contour
    for contour in contours:
        (x,y,w,h)=cv2.boundingRect(contour)
        if(cv2.contourArea(contour)<2000):
            continue
        cv2.rectangle(frame1,(x,y),(x+w,y+h),(0,25,45),3)
    cv2.imshow("Video",frame1)
    frame1=frame2
    _,frame2=cap.read()
    if cv2.waitKey(40)==27:
        break
cv2.destroyAllWindows()
cap.release()